// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB162l-l4B4MvUrsXWHbexOxoIoHBUGWBI',
    appId: '1:15610913252:web:573b6d89e18bb5123927f1',
    messagingSenderId: '15610913252',
    projectId: 'grade-tracker-36c6d',
    authDomain: 'grade-tracker-36c6d.firebaseapp.com',
    storageBucket: 'grade-tracker-36c6d.appspot.com',
    measurementId: 'G-DQWER5B2Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjxBKosgaqHW0dQnQg7zQuVj1qGOGs2n0',
    appId: '1:15610913252:android:e96f3d4125bb18b53927f1',
    messagingSenderId: '15610913252',
    projectId: 'grade-tracker-36c6d',
    storageBucket: 'grade-tracker-36c6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdWiBhtl0HoR1vOR3XWCapYlekPQ190EA',
    appId: '1:15610913252:ios:be2b0d29019fa78b3927f1',
    messagingSenderId: '15610913252',
    projectId: 'grade-tracker-36c6d',
    storageBucket: 'grade-tracker-36c6d.appspot.com',
    iosBundleId: 'com.example.gradeApp',
  );
}
